---
abstract: 'Perl module for JSON output for structured errors.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  Cwd: 0
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Spec::Functions: 0
  FindBin: 0
  IO::CaptureOutput: 1.02
  JSON: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Pure-JSON
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Error::Pure::Output::JSON: 0.09
  Error::Pure::Utils: 0.18
  Exporter: 0
  List::MoreUtils: 0
  Readonly: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Error-Pure-JSON
  homepage: https://github.com/tupinek/Error-Pure-JSON
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Error-Pure-JSON
version: '0.08'
